from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from typing import Optional

router = APIRouter()

class ExportRequest(BaseModel):
    analysis: dict
    language: Optional[str] = "English"


@router.post("/export/txt", response_class=PlainTextResponse, summary="Export as plain text")
async def export_txt(req: ExportRequest):
    try:
        d = req.analysis
        lines = [
            "🏥 MEDBUDDY HEALTH SUMMARY",
            "=" * 40,
            "",
            f"📌 SUMMARY",
            d.get("summary_en", ""),
            "",
            "🔬 DIAGNOSIS",
            d.get("diagnosis", {}).get("simple_english", "Not available"),
            "",
            "💊 MEDICATIONS",
        ]
        for med in d.get("medications", []):
            lines.append(f"  • {med.get('name')} {med.get('dosage')} — {med.get('timing')} — {med.get('duration')}")
            if med.get("simple_instruction"):
                lines.append(f"    {med.get('simple_instruction')}")

        lines += ["", "⚠️ SIDE EFFECTS"]
        for se in d.get("side_effects", []):
            lines.append(f"  {se.get('icon','•')} [{se.get('severity','').upper()}] {se.get('text')}")

        lines += ["", f"🚨 {d.get('emergency', '')}", "", "✅ FOLLOW-UP CHECKLIST"]
        for item in d.get("checklist", []):
            lines.append(f"  ☐ [{item.get('category')}] {item.get('text')}")

        if d.get("recovery_note"):
            lines += ["", f"📅 Recovery: {d['recovery_note']}"]

        lines += [
            "",
            "—" * 40,
            "Generated by Aushadh AI AI — IAR Udaan Hackathon 2026",
            "⚕️ Always consult your physician for medical decisions.",
        ]
        return "\n".join(lines)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Export failed: {str(e)}")
